---
- hosts: cluster_hosts
  remote_user: "{{ admin_user }}"
  become: yes
  become_method: sudo
  gather_facts: yes
  tasks:
  - name: Uname
    command: "uname -a"
    register: result

  - debug:
      var: result.stdout

  - name: Get facts for dev1-master-lb-publicip
    azure_rm_publicip_facts:
      resource_group: rg-beta-ocp
      name: dev1-master-lb-publicip
