---
- hosts: cluster_hosts
  remote_user: "{{ admin_user }}"
  become: yes
  become_method: sudo
  gather_facts: no
  tasks:
  - name: Uname
    command: "uname -a"
    register: result

  - debug:
      var: result.stdout

  - debug:
      var: "{{ hostvars[inventory_hostname]['ansible_host'] }}"

  - debug:
      var: "{{ ternary(hostvars[inventory_hostname]['ansible_host'] }}"

  - debug:
      var: "{{ hostvars[inventory_hostname]['ansible_ssh_host'] }}"
