---
- hosts: cluster_hosts
  remote_user: "{{ admin_user }}"
  become: yes
  become_method: sudo
  gather_facts: yes
  tasks:
  - name: Uname
    command: "uname -a"
    register: result
  - debug:
      var: result.stdout
  - name: "Get facts for rg-beta-ocp"
    azure_rm_resourcegroup_facts:
      name: rg-beta-ocp
