---
- hosts: masters[0]
  gather_facts: no
  become: yes
  become_method: sudo
  tasks:
    - name: "Setup registry storage : populate /home/{{ ansible_user }}/azure-files-secret.yml"
      copy:
        dest: "/home/{{ ansible_user }}/azure-files-secret.yml"
        content: |
         apiVersion: v1
         kind: Secret
         metadata:
           name: azure-file-secret
         type: Opaque
         data:
           azurestorageaccountname: "{{ registrysa | b64encode }}"
           azurestorageaccountkey: "{{ registrysa_account_key | b64encode }}"

    - name: "oc delete secret azure-file-secret --ignore-not-found=true -n openshift"
      shell: "oc delete secret azure-file-secret --ignore-not-found=true -n openshift"

    - name: "oc create -f /home/{{ ansible_user }}/azure-files-secret.yml -n openshift"
      shell: "oc create -f /home/{{ ansible_user }}/azure-files-secret.yml -n openshift"

