---
- hosts: cluster_hosts
  gather_facts: no
  serial: 1
  become: yes
  vars:
    azure_conf_dir: /etc/origin/cloudprovider
    azure_conf: "{{ azure_conf_dir }}/azure.conf"

  tasks:
  - name: make sure {{ azure_conf_dir }} exists
    file:
      state: directory
      path: "{{ azure_conf_dir }}"

  - name: populate {{ azure_conf }}
    copy:
      dest: "{{ azure_conf }}"
      content: |
        {
          "aadClientId": "{{ aadclientid }}",
          "aadClientSecret": "{{ aadclientsecret }}",
          "aadTenantId": "{{ tenantid }}",
          "subscriptionId": "{{ subscriptionid }}",
          "tenantId": "{{ tenantid }}",
          "resourceGroup": "{{ resourcegroup }}",
          "location": "{{ location }}",
          "cloud": "{{ cloudname }}"
        }


