---
- hosts: masters[0]
  gather_facts: no
  become: yes
  become_method: sudo
  vars:
    description: "Set registry to use Azure Storage"
  tasks:
  tasks:
    - name: "populate /home/{{ ansible_user }}/registrystorage.yml"
      copy:
        dest: "/home/{{ ansible_user }}/registrystorage.yml"
        content: |
          version: 0.1
          log:
            level: debug
          http:
            addr: :5000
          storage:
            cache:
              blobdescriptor: inmemory
            delete:
              enabled: true
            azure:
              accountname: "ocpstacc"
              accountkey:  "UBilB63WKlMXSbMSvTY8FTy4zSoqa3SaYzrnq6OjGM7fA4LQ8SJ5Ot8zLvmeH6tJqjcTo/NNr8PqIqo5YLGiAA=="
              container: registry
              realm: core.windows.net
           auth:
            openshift:
              realm: openshift
          middleware:
            registry:
              - name: openshift
            repository:
              - name: openshift
                options:
                  acceptschema2: false
                  pullthrough: true
                  enforcequota: false
                  projectcachettl: 1m
                  blobrepositorycachettl: 10m
             storage:
               - name: openshift



  - name: "oc secrets new registry-config config.yaml=/home/{{ ansible_user }}/registrystorage.yml  -n default"
    shell: "oc secrets new registry-config config.yaml=/home/{{ ansible_user }}/registrystorage.yml -n default"

  - name: "oc volume dc/docker-registry --add --type=secret --secret-name=registry-config -m /etc/docker/registry/ -n default"
    shell: "oc volume dc/docker-registry --add --type=secret --secret-name=registry-config -m /etc/docker/registry/ -n default"

  - name: "oc set env dc/docker-registry REGISTRY_CONFIGURATION_PATH=/etc/docker/registry/config.yaml -n default"
    shell: "oc set env dc/docker-registry REGISTRY_CONFIGURATION_PATH=/etc/docker/registry/config.yaml -n default"

