version: 0.1
log:
  level: debug
http:
  addr: :5000
storage:
  cache:
    blobdescriptor: inmemory
  delete:
    enabled: true
  azure:
    accountname: "ocpstacc"
    accountkey:  "UBilB63WKlMXSbMSvTY8FTy4zSoqa3SaYzrnq6OjGM7fA4LQ8SJ5Ot8zLvmeH6tJqjcTo/NNr8PqIqo5YLGiAA=="
    container: registry
    realm: core.windows.net
auth:
  openshift:
    realm: openshift
middleware:
  registry:
    - name: openshift
  repository:
    - name: openshift
      options:
        acceptschema2: false
        pullthrough: true
        enforcequota: false
        projectcachettl: 1m
        blobrepositorycachettl: 10m
  storage:
    - name: openshift