---
env_id: "dev1"
ansible_user: ocpadmin
ansible_ssh_user: ocpadmin
users_home: /root
admin_user: ocpadmin

hosting_infrastructure: azure
storage_kind: managed
storage_account_name: sabetaopcp20180503
resourcegroup: "{{ ocp_rg_name }}"
location: "{{ azure_zone }}"

ocp_rg_name: "{{ env_id }}-ocp-rg"

azure_zone: "{{ lookup('env','LOCATION') }}"
tenantid: "{{ lookup('env','TENANTID') }}"
subscriptionid: "{{ lookup('env','SUBSCRIPTIONID') }}"
aadclientid: "{{ lookup('env','AADCLIENTID') }}"
aadclientsecret: "{{ lookup('env','AADCLIENTSECRET') }}"
cloudname: "{{ lookup('env','CLOUDNAME') }}"
registrysa: "{{ lookup('env','REGISTRYSA') }}"
registrysa_account_key: "{{ lookup('env','ACCOUNTKEY') }}"

# DNS configurations
# the 'dns_domain' will be used as the base domain for the deployment and has
# to be a domain that is managed by Azure DNS within your Azure subscription
# the 'dns_nameservers' is a list of DNS resolvers the cluster should use
dns_domain: "nip.io"

public_key: "{{ users_home }}/.ssh/id_rsa.pub"
private_key: "{{ users_home }}/.ssh/id_rsa"
ssh_publickey: "{{ lookup('file', '{{ users_home }}/.ssh/id_rsa.pub') }}"

master_vm_size: Standard_DS2_v2
master_vm_name: "{{ env_id }}-ocp-master"
master_docker_vol_size: 50
num_masters: 3

infra_vm_size: Standard_D4s_v3
infra_vm_name: "{{ env_id }}-ocp-infra"
infra_docker_vol_size: 50
num_infras: 2

app_vm_size: Standard_DS2_v2
app_vm_name: "{{ env_id }}-ocp-app"
app_docker_vol_size: 50
num_apps: 3


storage_account_type: Premium_LRS
managed_disk_type: Standard_LRS

# Specify the version of docker to use
docker_version: "1.13.*"

# Docker Storage configuration variables - for all nodes
# - default values are "/dev/xvdb" and "40"
docker_storage_block_device: "/dev/sdc"
docker_volume_size: "50"

# Tags and names used to identify the instances
# Note: Be careful when changing these as the tools rely on some of these values
# to be set correctly.
master_name: master
etcd_name: etcd
infra_node_name: infra-node
app_node_name: app-node
cns_node_name: cns

group_masters_tag: masters_azure
group_infra_nodes_tag: infra_nodes_azure
group_app_nodes_tag: app_nodes_azure
group_cns_nodes_tag: cns_nodes_azure

labels_masters_tag: "{region: default}"
labels_infra_nodes_tag: "{region: infra}"
labels_app_nodes_tag: "{region: primary}"
labels_cns_nodes_tag: "{region: primary}"


# Subscription Management Details
rhsm_register: True
rhsm_repos:
  - "rhel-7-server-rpms"
  - "rhel-7-server-ose-3.9-rpms"
  - "rhel-7-server-extras-rpms"
  - "rhel-7-fast-datapath-rpms"
  - "rhel-7-server-ansible-2.5-rpms"

# Keep this to use Red Hat Satellite:
#rhsm_server_hostname: 'sat-6.example.com'
#rhsm_org_id: 'CASL_ORG'
#rhsm_activationkey: 'casl-latest'

# Uncomment the following to use RHSM username, password and optionally pool:
rhsm_username: "{{ lookup('env','RHDN_USERNAME') }}"
rhsm_password: "{{ lookup('env','RHDN_PASSWORD') }}"
# leave commented out if you want to `--auto-attach` a pool
rhsm_pool: "{{ lookup('env','RHDN_POOL_ID') }}"


azure_create_rg: true
azure_create_vnet: true
azure_create_subnets: true
azure_create_availability_sets: true
azure_create_nics: true
azure_configure_security_groups: true
azure_create_loadbalancers: true
azure_storage_account: true
azure_create_master_instances: true
azure_create_infra_instances: true
azure_create_app_instances: true



ocp_vnet_name: "{{ env_id }}-ocp-vnet"
ocp_vnet_cidr: 10.228.8.0/21

image_offer: RHEL
image_publisher: RedHat
image_sku: '7.4'
image_version: latest

master_availabilityset_name: master_availabilityset
infra_availabilityset_name: infra_availabilityset
app_availabilityset_name: app_availabilityset

master_subnet_name: "{{ env_id }}-master-subnet"
master_subnet_cidr: 10.228.8.0/24
infra_subnet_name: "{{ env_id }}-infra-subnet"
infra_subnet_cidr: 10.228.9.0/24
app_subnet_name: "{{ env_id }}-app-subnet"
app_subnet_cidr : 10.228.10.0/24

master_networkinterface_name: "{{ env_id }}-master-nic"
infra_networkinterface_name: "{{ env_id }}-infra-nic"
app_networkinterface_name: "{{ env_id }}-app-nic"

master_sec_group: "{{ master_networkinterface_name }}"
infra_sec_group: "{{ infra_networkinterface_name }}"
app_sec_group: "{{ app_networkinterface_name }}"

master_lb_name: "{{ env_id }}-master-lb"
master_lb_public_ip_name: "{{ env_id }}-master-lb-publicip"
infra_lb_name: "{{ env_id }}-infra_lb"
infra_lb_public_ip_name: "{{ env_id }}-infra-lb-publicip"

