---
ansible_user: ocpadmin
ansible_ssh_user: ocpadmin
ansible_become: yes
openshift_install_examples: true
deployment_type: openshift-enterprise
openshift_release: v3.9
docker_udev_workaround: True
openshift_use_dnsmasq: true
openshift_master_default_subdomain: "apps.{{ env_id }}.digitaldevops.net"
openshift_override_hostname_check: true
osm_use_cockpit: true
os_sdn_network_plugin_name: 'redhat/openshift-ovs-multitenant'
openshift_master_api_port: 443
openshift_master_console_port: 443
osm_default_node_selector: 'region=app'
openshift_disable_check: disk_availability,docker_storage,memory_availability,docker_image_availability,package_version
openshift_cloudprovider_kind: azure

# default selectors for router and registry services
openshift_router_selector: 'region=infra'
openshift_registry_selector: 'region=infra'

# Deploy Service Catalog
# openshift_enable_service_catalog: false

# template_service_broker_install: false
template_service_broker_selector: {"region":"infra"}

# Type of clustering being used by OCP
openshift_master_cluster_method: native

# Addresses for connecting to the OpenShift master nodes
openshift_master_cluster_hostname: $MASTERPUBLICIPHOSTNAME
openshift_master_cluster_public_hostname: $MASTERPUBLICIPHOSTNAME
openshift_master_cluster_public_vip: $MASTERPUBLICIPADDRESS

# Enable HTPasswdPasswordIdentityProvider
openshift_master_identity_providers: [{'name': 'htpasswd_auth', 'login': 'true', 'challenge': 'true', 'kind': 'HTPasswdPasswordIdentityProvider', 'filename': '/etc/origin/master/htpasswd'}]

# Setup metrics
openshift_metrics_install_metrics: false
openshift_metrics_start_cluster: true
openshift_metrics_hawkular_nodeselector: {"region":"infra"}
openshift_metrics_cassandra_nodeselector: {"region":"infra"}
openshift_metrics_heapster_nodeselector: {"region":"infra"}
openshift_hosted_metrics_public_url: https://metrics.$ROUTING/hawkular/metrics

# Setup logging
openshift_logging_install_logging: false
openshift_logging_fluentd_nodeselector: {"logging":"true"}
openshift_logging_es_nodeselector: {"region":"infra"}
openshift_logging_kibana_nodeselector: {"region":"infra"}
openshift_logging_curator_nodeselector: {"region":"infra"}
openshift_master_logging_public_url: https://kibana.$ROUTING
openshift_logging_master_public_url: https://$MASTERPUBLICIPHOSTNAME:443

#Certs
openshift_master_named_certificates: [{"certfile": "/root/certs/digitaldevops.net.cer", "keyfile": "/root/certs/digitaldevops.net.key", "cafile": "/root/certs/ca.cer"}]
openshift_hosted_router_certificate: {"certfile": "/root/certs/digitaldevops.net.cer", "keyfile": "/root/certs/digitaldevops.net.key", "cafile": "/root/certs/ca.cer"}
openshift_hosted_registry_routecertificates: {"certfile": "/root/certs/digitaldevops.net.cer", "keyfile": "/root/certs/digitaldevops.net.key", "cafile": "/root/certs/ca.cer"}
openshift_metrics_hawkular_ca: /root/certs/ca.cer
openshift_metrics_hawkular_cert: /root/certs/digitaldevops.net.cer
openshift_metrics_hawkular_key: /root/certs/digitaldevops.net.key
openshift_logging_kibana_key: /root/certs/digitaldevops.net.key
openshift_logging_kibana_cert: /root/certs/digitaldevops.net.cer
openshift_logging_kibana_ca: /root/certs/ca.cer
openshift_node_kubelet_args:
  minimum-container-ttl-duration:
  - "10s"
  maximum-dead-containers-per-container:
  - "2"
  maximum-dead-containers:
  - "50"
  pods-per-core:
  - '10'
  max-pods:
  - '250'
  image-gc-high-threshold:
  - '80'
  image-gc-low-threshold:
  - '60'
