- name: Create App VM
  azure_rm_virtualmachine:
    resource_group: "{{ ocp_rg_name }}"
    name: "{{ app_vm_name }}-{{ item }}"
    vm_size: "{{ app_vm_size }}"
    os_type: Linux
    ssh_password_enabled: false
    managed_disk_type: "{{ managed_disk_type }}"
    admin_username: "{{ admin_user }}"
    subnet_name: "{{ app_subnet_name }}"
    availability_set: "{{ app_availabilityset_name }}"
    ssh_public_keys:
      - path: "/home/{{ admin_user }}/.ssh/authorized_keys"
        key_data: "{{ ssh_publickey }}"
    network_interface_names:
    - "{{ app_networkinterface_name }}-{{ item }}"
    data_disks:
    - lun: 0
      disk_size_gb: "{{ app_docker_vol_size }}"
      managed_disk_type: "{{ managed_disk_type }}"
    image:
      offer: "{{ image_offer }}"
      publisher: "{{ image_publisher }}"
      sku: "{{ image_sku }}"
      version: "{{ image_version }}"
    tags:
      app: "true"
      type: "app"
      name: "{{ app_vm_name }}-{{ item }}"
      group: "{{ group_app_nodes_tag }}"
      node_labels: "{{ labels_app_nodes_tag }}"
      env_id: "{{ env_id }}"
  with_sequence:
    count="{{ num_apps }}"