- name: Create Infra VM scaleset
  azure_rm_virtualmachine_scaleset:
    resource_group: "{{ ocp_rg_name }}"
    name: "{{ infra_vm_name }}-scaleset"
    vm_size: "{{ infra_vm_size }}"
    capacity: "{{ num_infras }}"
    os_type: Linux
    ssh_password_enabled: false
    load_balancer: "{{ infra_lb_name }}"
    managed_disk_type: "{{ storage_account_type }}"
    admin_username: "{{ admin_user }}"
    virtual_network_name: "{{ ocp_vnet_name }}"
    subnet_name: "{{ infra_subnet_name }}"
    upgrade_policy: Manual
    ssh_public_keys:
      - path: "/home/{{ admin_user }}/.ssh/authorized_keys"
        key_data: "{{ ssh_publickey }}"
    data_disks:
    - lun: 0
      disk_size_gb: "{{ infra_docker_vol_size }}"
      caching: ReadWrite
      managed_disk_type: "{{ storage_account_type }}"
    image:
      offer: "{{ image_offer }}"
      publisher: "{{ image_publisher }}"
      sku: "{{ image_sku }}"
      version: "{{ image_version }}"
    tags:
      infra: "true"
      type: "infra"
      name: "{{ infra_vm_name }}"
      group: "{{ group_infras_tag }}"
      node_labels: "{{ labels_infras_tag }}"
      env_id: "{{ env_id }}"