---
- name: Fail when delete_vpc is not defined
  debug:
    msg: "delete_vpc boolean variable must be specified to remove the Cluster"
  failed_when:
    - delete_vpc is not defined
    - operation == "absent"

- name: Fail when ~/.azure/credentials does not exist
  stat:
    path: ~/.azure/credentials
  register: azure_credentials

- debug:
    msg: "~/.azure/credentials does not exist"
  failed_when: azure_credentials.stat.exists == False