- name: remove master vms and all storage
  azure_rm_virtualmachine_scaleset:
    resource_group: "{{ ocp_rg_name }}"
    name: "{{ master_vm_name }}-scaleset"
    state: absent
    remove_on_absent:
      - virtual_storage

- name: remove infra vms and all storage
  azure_rm_virtualmachine_scaleset:
    resource_group: "{{ ocp_rg_name }}"
    name: "{{ infra_vm_name }}-scaleset"
    state: absent
    remove_on_absent:
      - virtual_storage

- name: remove app vms and all storage
  azure_rm_virtualmachine_scaleset:
    resource_group: "{{ ocp_rg_name }}"
    name: "{{ app_vm_name }}-scaleset"
    state: absent
    remove_on_absent:
      - virtual_storage
  with_sequence:
    count="{{ num_apps }}"